"""
agent/image/generator.py

Generates cinematic images for each script segment using the Pollinations.ai
authenticated API (gen.pollinations.ai).

Key design decisions:
- Prompts generated by LLM based on actual segment text (not keyword matching)
- Sequential generation (no threading) — simple, predictable, rate-limit safe
- Fallback model chain: flux → nanobanana → kontext
  Every segment MUST produce an image; only move to the next model if all
  retries on the current one are exhausted.
- 1920×1080 resolution (16:9 Full HD)
- API key read from environment variable 'pollination_api'
- Prompts saved to {project_dir}/images/image_prompts.json
"""

import json
import logging
import os
import time
import urllib.parse
from pathlib import Path

import requests

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

BASE_URL = "https://gen.pollinations.ai"
IMAGE_WIDTH = 1920
IMAGE_HEIGHT = 1080
FALLBACK_MODELS = ["z-image-turbo", "p-image", "flux", "gpt-image-1-mini"]

RETRIES_PER_MODEL = 3
RETRY_DELAY = 5        # seconds between retries within the same model
SEGMENT_DELAY = 2      # seconds between segments
RATE_LIMIT_WAIT = 30   # seconds to wait on 429
LLM_PROMPT_TEMPERATURE = 0.4
LLM_PROMPT_MODEL = "gpt-5.4"  # model used for image prompt generation
BALANCE_WAIT = 60      # seconds to wait when balance is insufficient (402)
STYLE_SUFFIX = (
    "Image style description: Horizontal wide-screen, 16:9 aspect ratio, realistic physics, "
    "realistic geometry, real-life snapshot, ultra-realistic, photorealistic, real-world textures, "
    "physically accurate lighting, soft shadows, realistic reflections, true-to-life proportions, "
    "not staged, not over-posed."
)


class InsufficientBalanceError(Exception):
    """Raised when the Pollinations API returns 402 (not enough pollen)."""

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Internal: prompt generation via LLM
# ---------------------------------------------------------------------------

_PROMPT_SYSTEM = """You are a cinematographer describing a single PHOTOGRAPHIC FRAME for Stable Diffusion image generation. Given a script segment, produce one image prompt capturing the most visually striking frozen moment from the scene.

STRICT RULES:
1. SCENE FIRST — lead with the most cinematic visual subject of THIS specific scene: a landscape, an object, an action, or a character. Do NOT always start with a character.
2. ENTITIES — if entities are listed under ENTITIES IN THIS SCENE, use their EXACT name in the composition (e.g. "Dr. Elara Voss in the foreground") — do NOT describe their physical appearance here, their visual attributes will be inserted inline automatically.
3. STATIC IMAGE ONLY — absolutely NO motion or animation words. COMPLETELY BANNED: dancing, flickering, creeping, swirling, drifting, floating, waving, moving, flowing, blowing, casting, playing, echoing, morphing, spreading, seeping, trembling, pulsing, spinning, rotating.
   INSTEAD use the frozen STATE: "a lit candle" not "flickering candle", "long angular shadows" not "shadows creeping".
4. Every prompt MUST be unique to its segment — capture what visually distinguishes THIS scene.
5. NO ABSTRACTIONS — every element must be described with concrete, visible specifics.
   COMPLETELY FORBIDDEN words and phrases: "mysterious", "ominous", "eerie", "sense of dread", "feeling of isolation", "tense atmosphere", "isolation and fear", "muted colors", "desolate atmosphere", "haunting", "foreboding", "unsettling", "otherworldly", "surreal", "dramatic atmosphere", "tense stillness".
   INSTEAD describe what the camera literally sees: exact colors ("rust-orange sky", "pale grey dust"), exact light source and angle ("cold white lamp at 45 degrees from the left"), exact surface textures ("cracked dry mud", "polished chrome with micro-scratches"), exact distances ("two meters apart", "in the far left corner"), exact shadows ("a 60 cm sharp black shadow on pale dust").
6. Describe only what a camera lens can capture: composition, setting, objects, light source, color tones, framing angle, surface materials.
7. CINEMATIC COMPOSITION — every prompt must apply these rules:
   - Use rule of thirds or golden ratio placement for the focal point — never centered or symmetrical.
   - Include foreground, midground, and background elements to create depth and layering.
   - Use leading lines, perspective, or framing elements to guide the eye.
   - Apply dramatic, high-contrast lighting with a clear directional source. CRITICAL: describe light only as it falls on surfaces — direction, color, and shadow it creates (e.g. "cold white sunlight from the upper left cuts hard shadows across the dust"). NEVER describe a physical lamp, projector, spotlight, or light fixture as a visible object in the frame unless it is a named story prop.
   - MANDATORY CAMERA ANGLE: the task will specify the required opening camera angle for this scene — begin your prompt with that angle. NEVER substitute or ignore it.
   - Capture a specific mid-action moment: a hand reaching, a body mid-turn, weight shifted on one foot, head tilted — never a stiff neutral pose.
   - If the main character appears across multiple scenes: vary the pose, body position, and framing to match the assigned angle — no repeated stances.
   - Avoid static, symmetrical, or stiff compositions. Prioritize tension, spontaneity, and narrative moment.
8. EMOTION — for every named character visible in the scene, include EXACTLY ONE concrete visible emotion expressed through posture, face, or hands. Express it as a physical description only: "jaw clenched", "eyes wide", "shoulders pulled back", "grip tight on the railing" — NOT abstract words like "fear" or "determination".
9. LANDSCAPE ORIENTATION & REALISM — the image must be horizontal wide-screen 16:9. End EVERY prompt with exactly this suffix (copy verbatim):
    "Image style description: Horizontal wide-screen, 16:9 aspect ratio, realistic physics, realistic geometry, real-life snapshot, ultra-realistic, photorealistic, real-world textures, physically accurate lighting, soft shadows, realistic reflections, true-to-life proportions, not staged, not over-posed."
10. Max 200 words — be descriptive and specific.
11. Output ONLY the prompt text. No quotes, no labels, no explanation.

FORMAT: Use complete sentences ending with periods. Each sentence covers one aspect.
Example: "High-angle shot from above looking down at Dr. Elara Voss at the left third of frame, her gloved hand pressed hard against a jagged basalt rock, jaw tight, eyes fixed straight ahead. Canyon walls of dark-red rock converge below her. Pale cold sunlight from the upper right creates a hard 80 cm shadow across the rust-red dust floor. Image style description: Horizontal wide-screen, 16:9 aspect ratio, realistic physics, realistic geometry, real-life snapshot, ultra-realistic, photorealistic, real-world textures, physically accurate lighting, soft shadows, realistic reflections, true-to-life proportions, not staged, not over-posed." """

# Mandatory camera angle rotation — one per segment index, cycles for > 9 segments
_ANGLE_ROTATION = [
    "low-angle shot from knee height looking upward at the scene",
    "high-angle shot from above looking down at the scene",
    "three-quarter front shot with subject at left third facing right",
    "dutch tilt shot with the horizon tilted approximately 20 degrees",
    "wide establishing shot placing subjects small within the full environment",
    "ground-level low-angle shot with the camera just above the soil",
    "close medium shot from slightly to the side, subject fills the center third",
    "medium shot from slightly behind and to the side, subject fills left third",
    "bird's-eye top-down view from directly overhead",
]

# ---------------------------------------------------------------------------
# Post-processing: remove / neutralise known motion words that slip through
# ---------------------------------------------------------------------------
import re as _re

_MOTION_REPLACEMENTS = [
    # pattern                           replacement
    (r'\bflickering\s+candle\b',        'lit candle'),
    (r'\bflickering\s+flame\b',         'candle flame'),
    (r'\bflickering\s+light\b',         'dim light'),
    (r'\bflickering\b',                 ''),
    (r'\bcreeping\s+shadows\b',         'deep shadows'),
    (r'\bshadows\s+creeping\b',         'deep shadows'),
    (r'\bdancing\s+shadows\b',          'dramatic shadows'),
    (r'\bshadows\s+dancing\b',          'dramatic shadows'),
    (r'\bcasting\s+shadows\b',          'with shadows'),
    (r'\bcasting\s+(?:long|angular|ominous|dark)\b', 'with'),
    (r'\bcasting\b',                    ''),
    (r'\bswirling\b',                   ''),
    (r'\bdrifting\b',                   ''),
    (r'\bseeping\b',                    ''),
    (r'\bechoing\b',                    ''),
    (r'\bplaying\s+(?:across|on)\b',   'on'),
    (r'\s{2,}',                         ' '),  # collapse double spaces
]


def _clean_motion_words(prompt: str) -> str:
    """Remove known motion/animation words that LLM occasionally sneaks in."""
    for pattern, replacement in _MOTION_REPLACEMENTS:
        prompt = _re.sub(pattern, replacement, prompt, flags=_re.IGNORECASE)
    return prompt.strip(' ,;')


def _normalize_style_suffix(prompt: str) -> str:
    """Force the exact canonical style suffix at the end of every prompt."""
    prompt = _re.sub(
        r'\s*Image style description:.*$',
        '',
        prompt,
        flags=_re.IGNORECASE | _re.DOTALL,
    ).rstrip('. ')
    return f"{prompt}. {STYLE_SUFFIX}"


def load_entities(project_dir: str | Path) -> list[dict]:
    """
    Load entity descriptions from {project_dir}/entities.json.
    Returns a flat list of {"name": str, "base_prompt": str} dicts.
    Returns an empty list if the file is missing or malformed.
    """
    path = Path(project_dir) / "entities.json"
    if not path.exists():
        return []
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        entities: list[dict] = []
        for category in ("characters", "animals", "objects"):
            for item in data.get(category, []):
                name = item.get("name", "").strip()
                # Characters may have multiple versions; use the first
                if category == "characters":
                    versions = item.get("versions", [])
                    base_prompt = versions[0].get("base_prompt", "") if versions else ""
                else:
                    base_prompt = item.get("base_prompt", "")
                if name and base_prompt:
                    entities.append({"name": name, "base_prompt": base_prompt})
        logger.debug("[image] Loaded %d entities from %s", len(entities), path)
        return entities
    except Exception as exc:
        logger.warning("[image] Failed to load entities.json (%s)", exc)
        return []


def _inject_entity_descriptions_inline(prompt: str, active: list[dict]) -> str:
    """
    Find the FIRST occurrence of each entity name in the LLM-generated prompt
    and replace it with "Name — base_prompt —" so visual attributes appear
    exactly where the entity is mentioned, not appended at the end.

    Sorts longest-name-first to avoid partial matches.
    """
    sorted_entities = sorted(active, key=lambda e: len(e["name"]), reverse=True)
    for ent in sorted_entities:
        name = ent["name"]
        desc = ent["base_prompt"].rstrip(". ")
        pattern = _re.compile(_re.escape(name), _re.IGNORECASE)
        replacement = f"{name} \u2014 {desc} \u2014"
        prompt = pattern.sub(replacement, prompt, count=1)
    return prompt


def _inject_entity_descriptions(text: str, entities: list[dict]) -> str:
    """
    Replace every entity name in the segment text with its visual base_prompt
    wrapped in square brackets.  The LLM then reads concrete visual attributes
    instead of abstract names, producing consistent Stable Diffusion prompts.

    Sorting longest-name-first avoids partial substitutions
    (e.g. "MARS" replacing part of "MARS-1").
    """
    if not entities:
        return text
    sorted_entities = sorted(entities, key=lambda e: len(e["name"]), reverse=True)
    for ent in sorted_entities:
        pattern = _re.compile(_re.escape(ent["name"]), _re.IGNORECASE)
        replacement = f"[{ent['base_prompt']}]"
        text = pattern.sub(replacement, text)
    return text


def extract_story_context(script_text: str, cache_path: "Path | None" = None) -> str:
    """
    Extract a short visual setting summary from the full script via one LLM call.
    Result is cached to cache_path so repeated pipeline runs skip re-generation.
    Returns empty string on failure (graceful degradation).
    """
    if cache_path and Path(cache_path).exists():
        cached = Path(cache_path).read_text(encoding="utf-8").strip()
        if cached:
            logger.info("[image] Story context loaded from cache: %s", cache_path)
            return cached
    try:
        from agent.tools import get_llm
        from langchain_core.messages import HumanMessage, SystemMessage
        llm = get_llm(temperature=0.3)
        system = (
            "Extract the visual setting of this script in max 20 words.\n"
            "Focus on: location, time period, visual style/genre, dominant colors, atmosphere.\n"
            "Output ONLY the phrase, nothing else.\n"
            'Example: "Mars surface, near-future sci-fi, desolate red rocky landscape, '
            'harsh sunlight, claustrophobic space suits"'
        )
        msg = llm.invoke([
            SystemMessage(content=system),
            HumanMessage(content=f"Script:\n{script_text[:3000]}"),
        ])
        context = msg.content.strip().strip('"').strip("'")
        if cache_path:
            Path(cache_path).parent.mkdir(parents=True, exist_ok=True)
            Path(cache_path).write_text(context, encoding="utf-8")
            logger.info("[image] Story context saved \u2192 %s", cache_path)
        logger.info("[image] Story context: %s", context)
        return context
    except Exception as exc:
        logger.warning("[image] Story context extraction failed (%s)", exc)
        return ""


def analyze_segment_entities(
    segments: list[dict],
    entities: list[dict],
    script_text: str,
    cache_path: "Path | None" = None,
) -> "dict[int, list[dict]]":
    """
    Use one LLM call to determine which entities appear in each segment,
    including when referenced by pronouns or implicitly.
    Returns {segment_index: [entity_dict, ...]}.
    Result is cached to avoid re-running on repeated pipeline calls.
    """
    if cache_path and Path(cache_path).exists():
        try:
            raw_cached = json.loads(Path(cache_path).read_text(encoding="utf-8"))
            entity_map = {e["name"]: e for e in entities}
            result = {int(k): [entity_map[n] for n in v if n in entity_map]
                      for k, v in raw_cached.items()}
            logger.info("[image] Segment entities loaded from cache: %s", cache_path)
            return result
        except Exception:
            pass

    if not entities:
        return {seg["segment_index"]: [] for seg in segments}

    entity_names = [e["name"] for e in entities]
    entity_map = {e["name"]: e for e in entities}
    segments_block = "\n".join(
        f"[Segment {seg['segment_index']}]: {seg.get('text', '')}"
        for seg in segments
    )

    try:
        from langchain_openai import ChatOpenAI
        from langchain_core.messages import HumanMessage, SystemMessage
        llm = ChatOpenAI(
            model=LLM_PROMPT_MODEL,
            temperature=0.0,
            api_key=os.environ.get("OPENAI_API_KEY"),
        )
        system = (
            "You are a script analyst. Given a full script and its segments, "
            "identify which specific entities appear in each segment — including "
            "when they are referenced by pronouns (she/he/her/it/they) or implicitly.\n"
            f"Entities to track: {json.dumps(entity_names)}\n\n"
            "Output ONLY valid JSON mapping segment number strings to arrays of entity "
            'names. Example: {"1": ["Dr. Elara Voss", "MARS-1"], "2": ["MARS-1"], "3": []}\n'
            "Include ALL segment numbers. Use exact entity names from the list."
        )
        msg = llm.invoke([
            SystemMessage(content=system),
            HumanMessage(content=(
                f"Full script:\n{script_text[:3000]}\n\n"
                f"Segments:\n{segments_block}"
            )),
        ])
        raw = msg.content.strip()
        if "```" in raw:
            raw = raw.split("```")[1].lstrip("json").strip()
        mapping = json.loads(raw)

        result = {
            seg["segment_index"]: [
                entity_map[n] for n in mapping.get(str(seg["segment_index"]), []) if n in entity_map
            ]
            for seg in segments
        }

        if cache_path:
            Path(cache_path).parent.mkdir(parents=True, exist_ok=True)
            Path(cache_path).write_text(
                json.dumps({str(k): [e["name"] for e in v] for k, v in result.items()},
                           ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
            logger.info("[image] Segment entities saved \u2192 %s", cache_path)

        for seg in segments:
            idx = seg["segment_index"]
            names = [e["name"] for e in result.get(idx, [])]
            logger.info("[image] Seg %d entities: %s", idx, names or "none")
        return result

    except Exception as exc:
        logger.warning("[image] Segment entity analysis failed (%s)", exc)
        return {seg["segment_index"]: [] for seg in segments}


def build_prompt(
    segment_text: str,
    segment_index: int | None = None,
    entities: list[dict] | None = None,
    global_context: str = "",
    segment_entities: "list[dict] | None" = None,
) -> str:
    """
    Generate a cinematic Stable Diffusion image prompt from a segment.

    Pipeline:
      1. Replace entity names in segment text with their visual base_prompt.
      2. Build an ENTITIES section listing every entity present in this scene
         (from segment_entities), covering pronoun / implicit references.
      3. Append global story context to the system message.
      4. Ask LLM to produce one static-frame image prompt (~1000 chars).
      5. Post-process to strip banned motion words.
    """
    try:
        from langchain_openai import ChatOpenAI
        from langchain_core.messages import HumanMessage, SystemMessage
        llm = ChatOpenAI(
            model=LLM_PROMPT_MODEL,
            temperature=LLM_PROMPT_TEMPERATURE,
            api_key=os.environ.get("OPENAI_API_KEY"),
        )

        # ── 1. Pass segment text as-is (entity descriptions appended after LLM output) ──
        enriched_text = segment_text

        # ── 2. List entity names present in this scene (no descriptions — appended later) ──
        active = segment_entities or []
        if active:
            entity_names_list = ", ".join(e["name"] for e in active)
            entity_section = f"\n\nENTITIES IN THIS SCENE: {entity_names_list}"
        else:
            entity_section = ""

        # ── 3. Build system message with global context appended ──────────────
        context_addendum = (
            f"\n\nSETTING CONTEXT — this must be present in every prompt: {global_context}"
            if global_context else ""
        )
        system_content = _PROMPT_SYSTEM + context_addendum

        label = f"Segment {segment_index}" if segment_index is not None else "Script segment"
        if segment_index is not None:
            angle = _ANGLE_ROTATION[(segment_index - 1) % len(_ANGLE_ROTATION)]
            angle_line = f"\n\nMANDATORY OPENING CAMERA ANGLE: {angle}"
        else:
            angle_line = ""
        msg = llm.invoke([
            SystemMessage(content=system_content),
            HumanMessage(content=f"{label}:{entity_section}{angle_line}\n\nScene text:\n{enriched_text}"),
        ])
        prompt = msg.content.strip().strip('"').strip("'")
        prompt = _clean_motion_words(prompt)

        # ── Inline-inject entity base_prompts at first name occurrence ────────
        if active:
            prompt = _inject_entity_descriptions_inline(prompt, active)

        # ── Force the exact canonical style suffix ───────────────────────────
        prompt = _normalize_style_suffix(prompt)

        logger.debug("[image] LLM prompt: %s", prompt)
        return prompt
    except Exception as exc:
        logger.warning("[image] LLM prompt generation failed (%s), using fallback", exc)
        return (
            "cinematic scene matching the narrative, dramatic atmospheric lighting, "
            "photorealistic, 8k, no people"
        )


def build_prompts_for_segments(
    segments: list[dict],
    entities: list[dict] | None = None,
    global_context: str = "",
    script_text: str = "",
) -> "dict[int, str]":
    """
    Generate image prompts for all segments in one batch.
    When script_text is provided, runs a one-shot LLM analysis to determine
    which entities appear in each segment (even via pronouns), then passes
    that mapping into each build_prompt call.
    Returns {segment_index: prompt}.
    """
    # Analyse which entities appear in each segment (pronoun-aware)
    segment_entity_map: dict[int, list[dict]] = {}
    if entities and script_text:
        cache_path = None  # caller can set; generate_all_images uses its own cache
        segment_entity_map = analyze_segment_entities(
            segments, entities, script_text
        )

    return {
        seg["segment_index"]: build_prompt(
            seg.get("text", ""),
            seg["segment_index"],
            entities,
            global_context,
            segment_entity_map.get(seg["segment_index"]),
        )
        for seg in segments
    }


# ---------------------------------------------------------------------------
# Internal: single image request
# ---------------------------------------------------------------------------

def _request_image(prompt: str, model: str, segment_idx: int, api_key: str) -> bytes | None:
    """
    Attempt to fetch one image from Pollinations.
    Returns raw bytes on success, None on any failure.
    Handles 429 by waiting RATE_LIMIT_WAIT before retrying (not counted as a retry).
    """
    encoded = urllib.parse.quote(prompt, safe="")
    url = (
        f"{BASE_URL}/image/{encoded}"
        f"?width={IMAGE_WIDTH}&height={IMAGE_HEIGHT}"
        f"&model={model}&seed={segment_idx * 17}"
    )
    headers = {"Authorization": f"Bearer {api_key}"}

    for attempt in range(1, RETRIES_PER_MODEL + 2):
        try:
            logger.debug(
                "[image] Seg %d model=%s attempt %d/%d",
                segment_idx, model, attempt, RETRIES_PER_MODEL + 1
            )
            resp = requests.get(url, headers=headers, timeout=120)

            if resp.status_code == 429:
                wait = int(resp.headers.get("Retry-After", RATE_LIMIT_WAIT))
                logger.warning(
                    "[image] Seg %d 429 rate-limit on %s — waiting %ds",
                    segment_idx, model, wait
                )
                time.sleep(wait)
                continue  # don't consume a retry slot

            if resp.status_code == 402:
                # Insufficient pollen balance — no point retrying same model
                logger.warning(
                    "[image] Seg %d 402 insufficient balance on %s — skip all models",
                    segment_idx, model
                )
                raise InsufficientBalanceError("Insufficient pollen balance")

            resp.raise_for_status()

            ctype = resp.headers.get("content-type", "")
            if "image" not in ctype:
                raise ValueError(f"Unexpected content-type: {ctype}")

            logger.info(
                "[image] Seg %d ✓ %s  %d KB",
                segment_idx, model, len(resp.content) // 1024
            )
            return resp.content

        except InsufficientBalanceError:
            raise  # propagate immediately, no retries

        except Exception as exc:
            logger.warning("[image] Seg %d model=%s attempt %d failed: %s",
                           segment_idx, model, attempt, exc)
            if attempt <= RETRIES_PER_MODEL:
                time.sleep(RETRY_DELAY)

    return None


# ---------------------------------------------------------------------------
# Public: generate one segment
# ---------------------------------------------------------------------------

def generate_image_for_segment(
    prompt: str,
    segment_idx: int,
    images_dir: Path,
    api_key: str,
) -> Path | None:
    """
    Generate and save one image for a segment.
    Tries models in FALLBACK_MODELS order.  All retries per model are exhausted
    before falling back to the next model.

    Returns the saved Path on success, None if every model fails.
    """
    images_dir.mkdir(parents=True, exist_ok=True)
    out_path = images_dir / f"segment_{segment_idx}.png"

    for model in FALLBACK_MODELS:
        logger.info("[image] Seg %d trying model=%s", segment_idx, model)
        try:
            data = _request_image(prompt, model, segment_idx, api_key)
        except InsufficientBalanceError:
            raise  # propagate to generate_all_images for a full wait
        if data:
            out_path.write_bytes(data)
            logger.info("[image] Seg %d saved → %s", segment_idx, out_path.name)
            return out_path
        logger.warning("[image] Seg %d model=%s exhausted, falling back", segment_idx, model)

    logger.error("[image] Seg %d FAILED all models", segment_idx)
    return None


# ---------------------------------------------------------------------------
# Public: generate all segments
# ---------------------------------------------------------------------------

def generate_all_images(
    segments: list[dict],
    project_dir: str | Path,
) -> list[dict]:
    """
    Generate images for every segment sequentially.
    Retries failed segments indefinitely (with growing back-off) until EVERY
    segment has a successfully saved image.  The pipeline cannot proceed until
    all images are present.

    Args:
        segments: List of dicts with at least keys 'segment_index' and 'text'.
        project_dir: Root project directory (images → {project_dir}/images/).

    Returns:
        List of result dicts, all guaranteed to have status "ok":
            {segment_index, prompt, status: "ok", image_path: str}
    """
    api_key = os.environ.get("pollination_api", "")
    if not api_key:
        raise RuntimeError(
            "Environment variable 'pollination_api' is not set. "
            "Set it to your Pollinations API key."
        )

    project_dir = Path(project_dir)
    images_dir = project_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)

    # ── 1. Generate all prompts via LLM upfront ───────────────────────────────
    entities = load_entities(project_dir)
    if entities:
        logger.info("[image] Loaded %d entities for prompt enrichment", len(entities))

    # Extract global story context from full script (cached after first run)
    global_context = ""
    script_path = project_dir / "script.txt"
    if script_path.exists():
        script_text = script_path.read_text(encoding="utf-8")
        context_cache = images_dir / "story_context.txt"
        global_context = extract_story_context(script_text, cache_path=context_cache)

    logger.info("[image] Generating image prompts via LLM for %d segments…", len(segments))
    prompts: dict[int, str] = build_prompts_for_segments(
        segments, entities, global_context, script_text=script_text if script_path.exists() else ""
    )

    # Save prompts to disk for inspection
    prompts_file = images_dir / "image_prompts.json"
    with open(prompts_file, "w", encoding="utf-8") as f:
        json.dump(
            [{"segment_index": idx, "prompt": p} for idx, p in sorted(prompts.items())],
            f, ensure_ascii=False, indent=2,
        )
    logger.info("[image] Prompts saved → %s", prompts_file)

    # ── 2. Build initial results list (all pending) ───────────────────────────
    results: list[dict] = []
    for seg in segments:
        idx = seg["segment_index"]
        results.append({
            "segment_index": idx,
            "prompt": prompts[idx],
            "status": "pending",
            "image_path": None,
        })

    global_pass = 0
    while True:
        pending = [r for r in results if r["status"] != "ok"]
        if not pending:
            break

        global_pass += 1
        logger.info(
            "[image] Pass %d — %d segment(s) still need images",
            global_pass, len(pending),
        )

        for r in pending:
            idx = r["segment_index"]
            logger.info("[image] Seg %d — prompt: %s", idx, r["prompt"][:80])

            try:
                saved_path = generate_image_for_segment(r["prompt"], idx, images_dir, api_key)
            except InsufficientBalanceError:
                logger.warning(
                    "[image] Balance insufficient \u2014 waiting %ds before retrying all segments",
                    BALANCE_WAIT,
                )
                time.sleep(BALANCE_WAIT)
                break  # restart the pass from the beginning

            if saved_path:
                r["status"] = "ok"
                r["image_path"] = str(saved_path)
            else:
                logger.warning("[image] Seg %d still failed — will retry", idx)

            time.sleep(SEGMENT_DELAY)

        still_pending = [r for r in results if r["status"] != "ok"]
        if still_pending:
            # Exponential back-off capped at 120s
            wait = min(30 * global_pass, 120)
            logger.warning(
                "[image] %d segment(s) failed in pass %d — waiting %ds before retry",
                len(still_pending), global_pass, wait,
            )
            time.sleep(wait)

    ok = sum(1 for r in results if r["status"] == "ok")
    logger.info("[image] Done: %d/%d images generated (all successful)", ok, len(results))
    return results
